/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.ramanji025.gradle.plugin.typescript

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'typescript.gradle.plugin.greeting' plugin.
 */
class TypescriptGradlePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("io.github.ramanji025.gradle.plugin")

        then:
        project.tasks.findByName("compileTypeScript") != null
    }
}
