/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.ramanji025.gradle.plugin.typescript

import spock.lang.Specification
import spock.lang.TempDir
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'typescript.gradle.plugin.greeting' plugin.
 */
class TypescriptGradlePluginPluginFunctionalTest extends Specification {
    @TempDir
    private File projectDir

    private getBuildFile() {
        new File(projectDir, "build.gradle")
    }

    private getSettingsFile() {
        new File(projectDir, "settings.gradle")
    }

    def "can run task"() {
        given:
        settingsFile << ""
        buildFile << """
plugins {
    id('io.github.ramanji025.gradle.plugin')
}
"""

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("compileTypeScript")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.length() > 0
    }
}
